---
- hosts: all
  become: true
  tasks:
  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/joincluster.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/joincluster.sh
